# Generated by Django 5.2.7 on 2025-12-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgeaweb", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banners/",
                verbose_name="Banner do Evento",
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="presenca_confirmada",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
                "db_table": "auditoria",
                "ordering": ["-data_hora"],
            },
        ),
    ]
